name: interactive-cp-map

services:
  nginx:
    build: .
    ports:
      - "1488:80"
    depends_on:
      - node-server
      - vue-app
      - osrm-server

  node-server:
    build: ./cp-backend
    expose:
      - "3000"

  vue-app:
    build:
      context: ./cp-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    expose:
      - "80"
  osrm-server:
    build: ./osrm-train-profile
    expose:
      - "5000"