name: interactive-cp-map

services:
  nginx:
    build: .
    ports:
      - "1488:80"
    depends_on:
      - node-server
      - vue-app
      - osrm-server

  node-server:
    build: 
      context: ./cp-backend
      args:
        CORS_ORIGIN: ${CORS_ORIGIN}
    expose:
      - "3000"
    volumes:
      - backend-data:/app/data

  vue-app:
    build:
      context: ./cp-frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    expose:
      - "80"
  osrm-server:
    build: ./osrm-train-profile
    expose:
      - 5000:5000

volumes:
  backend-data: